config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  get 'posts/index'
  devise_for :users
  root to: 'toppages#index'
  
  resources :users do
    member do
      get :followings
      get :followers
    end
    collection do
      get 'search'
    end
  end
  
  resources :recipes do
    collection do
      get 'search'
    end
  end
  
  # コメントはレシピページで表示するため、一覧や詳細などは不要、発言の取り消しや編集はさせない
  resources :posts,only:[:create]
  
  # フォロー・アンフォローの機能用
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :recipe
    belongs_to :user
    
    validates :content, presence: true
    
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :posts
     has_one_attached :image
    
    validates :title, presence: true
    validates :body, presence: true
    validates :base, presence: true
    validates :technique, presence: true
  
    enum base: {gin:0, rum:1, vodka:2, tequila:3, bourbon:4, scotch:5, rye:6, brandy:7, mezcal:8,liqueur:8,other:9}
    enum technique: { building:0, stiring:1, shaken:2, blending:3 ,other_way:4}
    
    def self.search(search)
        return Recipe.all unless search
        Recipe.where('title LIKE(?)', "%#{search}%")
        
    end
    
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one_attached :profile_image
  
  validates :username, presence: true
  
  has_many :recipes, :dependent => :destroy
  has_many :posts
  
  
  # 自分がフォローしているユーザーを参照
  has_many :relationships
  # ユーザーからフォローされている参照
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  
  # relationships　を経由してフォローフォロワーをとることでuser.followingsとしてとってこれる
  has_many :followings, through: :relationships, source: :follow
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  def follow(other_user)
    # 対象が自分自身でなければフォロー可能　selfは呼び出したユーザー
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    # すでにフォローしているか確認　selfは呼び出したユーザー selfはrelationshipテーブルにfollow_idがother_user_idのものを持っているか
    relationship = self.relationships.find_by(follow_id: other_user.id)
    # フォローしていればフォロー解除可能
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
    def self.search(search)
        return User.all unless search
        User.where('username LIKE ?', "%#{search}%")
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    def counts(user)
        @count_recipes = user.recipes.count
        @count_followings = user.followings.count
        @count_followers = user.followers.count
    end

    private

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:username])
    end
    

    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  

  
  def create
    @post = Post.new(post_params)
    if user_signed_in?
      if @post.save
        flash[:success] = '正常に投稿されました'
        redirect_to recipe_path(@post.recipe.id)
      else
        flash.now[:danger] = '投稿されませんでした。'
        render :new
      end
    else
      redirect_to new_user_session_path
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:user_id,:recipe_id,:content,:comment_number)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except:[:index,:show]
  before_action :correct_user, only:[:edit,:destroy]
  
  def index
    if params[:base]
      @recipes = Recipe.where(base: params[:base]).page(params[:page])
    elsif params[:technique]
      @recipes = Recipe.where(technique: params[:technique]).page(params[:page])
    else
      @recipes =  Recipe.order(id: :desc).page(params[:page]).per(25)
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @posts = Post.where(recipe_id:params[:id])
    @post = Post.new
  end

  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      flash[:success] = '正常に投稿されました'
      redirect_to recipe_path(@recipe)
    else
      flash.now[:danger] = '投稿されませんでした。'
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update(recipe_params)
      flash[:success] = '正常に更新されました'
      redirect_to @recipe
    else
      flash.now[:danger] = '更新されませんでした。'
      render :edit
    end
  end
  
  def destroy
    @recipe = Recipes.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
  end
  
  def search
    # .search はモデルに記述。:keywordでtitle（カクテル名）をあいまい検索するメソッド
    @recipes = Recipe.search(params[:keyword])
  end

  private
    def recipe_params
      params.require(:recipe).permit(:title,:body,:image,:base,:technique)
    end
    
    # def serch_params
    #   params.require(:recipe).permit(:keyword)
    # end
    
    def correct_user
      @recipe = current_user.recipes.find_by(id: params[:id])
      unless @recipe
        redirect_to root_url, alert:"不正なアクセスです。"
      end
    end
    
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action:user_signed_in?

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'フォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'フォローを解除しました。'
    redirect_to user
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    @recipes = Recipe.order(id: :desc).page(params[:page]).per(10)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except:[:index, :show]
  before_action :correct_user, only:[:edit,:destroy]
  
  
  def index
    @users = User.order(id: :desc).page(params[:page]).per(24)
  end

  def show
    @user = User.find(params[:id])
    @recipes = @user.recipes.order(id: :desc).page(params[:page])
    counts(@user)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'ユーザー情報は正常に更新されました'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザー情報は更新されませんでした。'
      render :edit
    end
  end
  
  # フォローしているユーザー表示
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  # フォローされているユーザーを表示
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end
  

  
  
  def search
    @users = User.search(params[:keyword])
  end
  
  
  
  
  
  
  
  private
  
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @user
  end
    
    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> role="alert""><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #0E0325">
      
  <a class="navbar-brand" href="/"><%= image_tag 'logo.png', :size => '30x30' %>Cocktailpad</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
          <li class="nav-item">
              <%= link_to "Recipes", recipes_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Users", users_path, class:"nav-link" %>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ベースから探す
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "ジン",recipes_path(base:"gin") ,class:"dropdown-item" %>
                <%= link_to "ラム",recipes_path(base:"rum") ,class:"dropdown-item" %>
                <%= link_to "ウォッカ",recipes_path(base:"vodka") ,class:"dropdown-item" %>
                <%= link_to "テキーラ",recipes_path(base:"tequila") ,class:"dropdown-item" %>
                <%= link_to "バーボン",recipes_path(base:"bourbon") ,class:"dropdown-item" %>
                <%= link_to "スコッチ",recipes_path(base:"scotch") ,class:"dropdown-item" %>
                <%= link_to "ライウイスキー",recipes_path(base:"rye") ,class:"dropdown-item" %>
                <%= link_to "メスカル",recipes_path(base:"mezcal") ,class:"dropdown-item" %>
                <%= link_to "リキュール",recipes_path(base:"liqueur") ,class:"dropdown-item" %>
                <%= link_to "その他",recipes_path(base:"other") ,class:"dropdown-item" %>
              </div>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                製法から探す
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <%= link_to "ビルド",recipes_path(technique:"building") ,class:"dropdown-item" %>
                <%= link_to "ステア",recipes_path(technique:"stiring") ,class:"dropdown-item" %>
                <%= link_to "シェイク",recipes_path(technique:"shaken") ,class:"dropdown-item" %>
                <%= link_to "ブレンド",recipes_path(technique:"blending") ,class:"dropdown-item" %>
                <%= link_to "その他",recipes_path(technique:"other_way") ,class:"dropdown-item" %>
              </div>
          </li>
      </ul>
  </div>
  
<div class="collapse navbar-collapse justify-content-start" id="navbarSupportedContent">
    <%= render 'layouts/search_form'%>
</div>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">


      <% if user_signed_in? %>
          <li class="nav-item dropdown ">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item"><%= link_to "マイページ", user_path(current_user) %></a>
                <a class="dropdown-item"><%= link_to "新規レシピ投稿", new_recipe_path %></a>
                <a class="dropdown-item"><%= link_to "フォロー", followings_user_path(current_user) %></a>
                <a class="dropdown-item"><%= link_to "フォロワー", followers_user_path(current_user) %></a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"><p class="text-center "><%= link_to "ログアウト",destroy_user_session_path, method: :delete %></p></a>
              </div>
          </li>
      
      
      <% else %>
      <li class="nav-item"><%= link_to "新規登録",new_user_registration_path, class:"btn btn-primary" %></li>
      <li class="nav-item"><%= link_to "ログイン", new_user_session_path, class:"btn btn-success" %></li>
      
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_search_form.html.erb
<%= form_with(url: search_recipes_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "Search", class: "search-input" %>
  <%= f.submit "Search", class: "search-btn" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Cocktialpad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <header class="mb-4">
      <%= render 'layouts/navbar' %>
    </header>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
    
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/posts/_post_form.html.erb
<h4>Comment Form</h4>
<div class="row justify-content-center">
    <div class="col-md-8">
    
        <%= form_with(model: post, local: true) do |f| %>
            <%= render 'layouts/error_messages' ,model: f.object %>
            <div class="form-group">
                <%= f.label :content ,"このレシピにあなたの意見を書き込んでください！"%>
                <%= f.text_area :content, size:"100x5",class:"form-control"  %>
            </div>
                
            <% if user_signed_in? %>
                <%= f.hidden_field :user_id, :value => current_user.id %>
                <%= f.hidden_field :recipe_id, :value => recipe.id %>
                <%= f.hidden_field :comment_number, :value => recipe.posts.count+1 %>
            <% end %>
            
            <%= f.submit "送信",class:"btn btn-primary"%>
        <% end %>
    </div>
</div>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/recipes/_recipe_form.html.erb
<div class="row justify-content-center">
    <div class="col-md-8">
    
        <%= form_with(model: recipe, local: true) do |f| %>
            <%= render 'layouts/error_messages' ,model: f.object %>
        
            <div class="form-group">
                <%= f.label :title,"カクテル名" %>
                <%= f.text_field :title, class:"form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :base,"ベーススピリッツ" %>
                <%= f.select :base, Recipe.bases.keys.map{|k|[I18n.t("enum.recipe.base.#{k}"), k]}, {},class:"form-control"%>
            </div>
            
            <div class="form-group">
                <%= f.label :technique,"製法" %>
                <%= f.select :technique, Recipe.techniques.keys.map{|k|[I18n.t("enum.recipe.technique.#{k}"), k]},{}, class:"form-control" %>
            </div>
            
            <div class="form-group">
                <%= f.label :body ,"作り方:材料や手順、こだわりポイントなどを入力してください。"%>
                <%= f.text_area :body, size:"20x5",class:"form-control"  %>
            </div>
                
            <div class="form-group">
                <%= f.label :iamge,"画像"%>
                <%= f.file_field :image, class:"form-control-file"  %>
            </div>
            
            <%= f.submit "Submit",class:"btn btn-primary"%>
        <% end %>
    </div>
</div>

app/views/recipes/_recipe_list.html.erb
<div class="row">
    <% recipes.each do |recipe| %>
        <div class="col">
            <div class="card shadow-sm mb-5" style="width: 8rem;">
                <% if recipe.image.attached? %>
                <%= link_to recipe_path(recipe) do %>
                    <%= image_tag recipe.image, class:"card-image-top rounded-top"%>
                <% end%>
                <% end%>
                <div class="card-body">
                    <%= link_to recipe_path(recipe) do %>
                        <h3 class="card-title text-dark"><%= recipe.title %></h3>
                    <% end%>
                </div>
                <% if user_signed_in? %>
                    <% if recipe.user.id == current_user.id %>
                    <ul class="list-group list-group-flush"> 
                        <li class="list-group-item"><%= link_to "Edit",edit_recipe_path(recipe) ,class:"card-link"%></li>
                        <li class="list-group-item"><%= link_to "Delete",recipe_path(recipe), method: :delte, data:{confirm:"削除します。よろしいですか？"},class:"card-link" %></li>
                    </ul>
                    <% end %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>
            <%= paginate recipes %>
    

app/views/recipes/edit.html.erb
<h1 class="text-center">レシピ編集</h1>
<%= render 'recipe_form' ,recipe:@recipe %>

app/views/recipes/index.html.erb
<h1 class="text-center">レシピ一覧</h1>
<br>
<br>
<%= render 'recipe_list', recipes:@recipes %>

app/views/recipes/new.html.erb
<h1 class="text-center">新規レシピ作成</h1>
<%= render 'recipe_form' ,recipe:@recipe %>

app/views/recipes/search.html.erb
<h1>検索結果</h1>
      <%= render 'recipe_list', recipes:@recipes %>

app/views/recipes/show.html.erb
<div class="row justify-content-md-center">
        <div class="card col-md-8">
            <% if @recipe.image.attached? %>
                <%= image_tag @recipe.image, class:"card-image-top w-100 h-auto"%>
            <% end %>
            <div class="card-body">
                <h1 class="card-title "><%= @recipe.title %></h1>
                
                <div class="row justify-content-end">
                    <% if user_signed_in? %>
                        <% if @recipe.user.id == current_user.id %>
                            <%= link_to "Edit",edit_recipe_path(@recipe) ,class:"btn btn-success btn-sm"%>
                            <%= link_to "Delete",recipe_path(@recipe), method: :delte, data:{confirm:"削除します。よろしいですか？"},class:"btn btn-danger btn-sm" %>
                        <% end %>
                    <% end %>
                </div>
                
                <div class="row ">
                    <div class="col align-self-start">
                        <p>投稿者：<%= link_to @recipe.user.username, user_path(@recipe.user.id)%><span class="text-muted"> | </span>
                        投稿日：<%= @recipe.created_at.strftime("%Y-%m-%d") %></p>
                    </div>
                </div>
                
                <h5 class="card-text">レシピ</h5>
                <hr class="mt-1">
                <p>ベース：<%= @recipe.base %></p>
                <p>製法：<%= @recipe.technique %></p>
                <p class="card-text"><%= simple_format @recipe.body %></p>
        </div>
                
<!--posts（レシピに対するコメント）を表示する-->

        <div  class="card-body">
            <%= render 'posts/post_form', post:@post ,recipe:@recipe %>
        </div>
        
        <% if @posts %>
            <% @posts.each do |post| %>
                <div class="card-body">
                    <div class="row justify-content-start">
                            <b>>><%= post.comment_number %></b>
                        <div class="col">
                            <% if post.user.profile_image.attached? %>
                                <%= image_tag post.user.profile_image ,fallback:"tender.png",size:"30x30"%>
                            <% end %>
                            <%= post.user.username%>
                            <%= post.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %>
                        </div>
                    </div>
                    <div>
                        <p><%= simple_format post.content %></p>
                    </div>
                </div>
            <% end %>
        <% else %>
            <div class="card-body">
                <p>まだコメントはありません。最初のコメントを書きましょう！</p>
            </div>
        <% end %>
        </div>
</div>

app/views/relationships/_follow_button.html.erb
<!--　自分にフォローボタンを作らない-->
<% if user_signed_in? %>
    <% unless current_user == user %>
            <!--フォローしていれば解除ボタン、していなければフォローボタン-->
            <% if current_user.following?(user) %>
                <%= form_with(model: current_user.relationships.find_by(follow_id: user.id), local: true, method: :delete) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォロー解除', class: 'btn btn-sm btn-danger btn-block' %>
                <% end %>
            <% else %>
                <%= form_with(model: current_user.relationships.build, local: true) do |f| %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= f.submit 'フォロー', class: 'btn btn-sm btn-primary  btn-block' %>
                <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/toppages/index.html.erb
<div class="center jumbotron">
  <div class="text-center text-light">
    <h1>カクテル掲示板へようこそ</h1>
    <p>あなたのカクテルに評価をもらいましょう！</p>
  </div>
</div>




<div class="row justify-content-md-start">
  <div class="col mb-5 ">
    <h2>新着カクテル</h2>
  </div>
  <div class="row justify-content-md-end">
    <div class="col">
      <%= link_to 'もっと見る >>',recipes_path ,class:"btn "%>
    </div>
  </div>
<%= render 'recipes/recipe_list', recipes:@recipes %>
</div>

app/views/users/_search_user_form.html.erb
<%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |f| %>
  <%= f.text_field :keyword, placeholder: "Search", class: "search-input" %>
  <%= f.submit "Search", class: "search-btn" %>
<% end %>

app/views/users/_user_list.html.erb
<% users.each do |user| %>
    <div class="container mt-5 d-flex justify-content-center">
        <div class="card p-3">
            <div class="d-flex align-items-center">
                <div class="image">
                    <% if user.profile_image.attached? %>
                        <%= link_to user_path(user) do%>
                            <%= image_tag user.profile_image, fallback:"tender.png",size:"120x120", class:"img-thumnail rounded-circle"%>
                        <% end %>
                    <% end %>
                    
                </div>
                <div class="ml-3 w-100">
                    <h4 class="mb-0 mt-0">
                        <%= link_to user_path(user) do%>
                            <%= user.username %>
                        <% end %>
                    </h4>
                    <div class="p-2 mt-1 bg-primary d-flex justify-content-between rounded text-white stats">
                        <div class="d-flex flex-column">
                            <span class="articles"><%= link_to "Recipes",recipe_path(user) %></span>
                            <span class="number1"><%= user.recipes.count %></span>
                        </div>
                        <div class="d-flex flex-column">
                            <span class="followers"><%= link_to "Followers",followers_user_path(user) %></span>
                            <span class="number2"> <%= user.followers.count %></span>
                        </div>
                        <div class="d-flex flex-column">
                            <span class="followers"><%= link_to "Followings",followings_user_path(user)%></span>
                            <span class="number3"><%= user.followings.count %></span>
                        </div>
                    </div>
                    <%= render 'relationships/follow_button', user: user %>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/users/followers.html.erb
<h1 class="text-center">Followers</h1>
<p class="text-center"><%= @user.username %>さんのフォロワー</p>

<%= render 'user_list', users: @followers%>

app/views/users/followings.html.erb
<h1 class="text-center">Following</h1>
<p class="text-center"><%= @user.username %>さんがフォワーしているユーザー</p>

<%= render 'user_list', users: @followings%>

app/views/users/index.html.erb
<h1 class="text-center">All Users</h1>
<div class="row justify-content-center">
    <%= render 'search_user_form' %>
</div>
    <%= render 'user_list', users: @users%>

app/views/users/search.html.erb
<h1>検索結果</h1>

      <%= render 'user_list', users:@users %>

app/views/users/show.html.erb
<div class="row py-5 px-4">
    <div class="col-md-9 mx-auto">
        <!-- Profile widget -->
        <div class="bg-white shadow rounded overflow-hidden">
            <div class="px-4 pt-0 pb-4 cover">
                <div class="media align-items-end profile-head">
                    <div class="profile mr-3">
                        <% if @user.profile_image.attached? %>
                            <%= image_tag @user.profile_image, fallback:"tender.png",size:"130x130", class:"rounded mb-2 img-thumbnail" %>
                        <% end %>
                        </div>
                    <div class="media-body mb-5 text-white">
                        <h4 class="mt-0 mb-0"><%= @user.username%></h4>
                        <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>New York</p>
                    </div>
                </div>
            </div>
            <div class="bg-light p-4 d-flex justify-content-end text-center">
                <ul class="list-inline mb-0">
                    
                    
                        <li class="list-inline-item">
                            <h5 class="font-weight-bold mb-0 d-block"><%= @count_recipes %></h5>
                            <small class="text-muted"> <i class="fas fa-image mr-1"></i>Recipes</small>
                        </li>
                        <li class="list-inline-item">
                            
                            <h5 class="font-weight-bold mb-0 d-block"><%= @count_followers %></h5>
                            <small class="text-muted"> <i class="fas fa-user mr-1"><%= link_to "Followers",followers_user_path %></i></small>
                        </li>
                        <li class="list-inline-item">
                            
                            <h5 class="font-weight-bold mb-0 d-block"><%= @count_followings %></h5>
                            <small class="text-muted"> <i class="fas fa-user mr-1"><%= link_to "Following",followings_user_path %></i></small>
                        </li>
                </ul>
            </div>
            <div class="bg-light p-4 d-flex justify-content-end text-center">
                    <% if user_signed_in? %>
                        
                        <% if @user.id == current_user.id %>
                                    <%= link_to "Edit profile",edit_user_path(@user),class:"btn btn-sm btn-outline-dark" %>
                                    <%= @user.email %>
                        <% end %>
                    <% end %>
                <!--フォローボタン-->
                <%= render 'relationships/follow_button', user: @user %>
            </div>
            <div class="px-4 py-3">
                <h5 class="mb-0">About</h5>
                <div class="p-4 rounded shadow-sm bg-light">
                    <p class="text break"><%= @user.profile%></p>
                </div>
            </div>
            <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Recipes</h5>
                </div>
                <div class="row">
                    <%= render 'recipes/recipe_list', recipes:@recipes %>
                </div>
            </div>
        </div>
    </div>
</div>